site_name: py-obsidianmd
site_url: https://selimrbd.github.io/py-obsidianmd/overview

nav:
  - Overview: index.md
  - Examples: examples.md
  - Reference:
      - note: reference/note.md
      - metadata: reference/metadata.md

plugins:
  - mkdocstrings

theme:
  name: material
  favicon: assets/obsidian.ico
  logo: assets/obsidian.png
